<?php

namespace Proxies\__CG__\GestionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vehiculos extends \GestionBundle\Entity\Vehiculos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'propietario', 'ubicaciones', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'id', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'tipo', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'marca', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'modelo', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'placa', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'color', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'createdAt', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'updatedAt');
        }

        return array('__isInitialized__', 'propietario', 'ubicaciones', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'id', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'tipo', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'marca', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'modelo', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'placa', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'color', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'createdAt', '' . "\0" . 'GestionBundle\\Entity\\Vehiculos' . "\0" . 'updatedAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vehiculos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarca($marca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarca', array($marca));

        return parent::setMarca($marca);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarca', array());

        return parent::getMarca();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelo($modelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelo', array($modelo));

        return parent::setModelo($modelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelo', array());

        return parent::getModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaca($placa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaca', array($placa));

        return parent::setPlaca($placa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaca', array());

        return parent::getPlaca();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', array($color));

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', array());

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtValue', array());

        return parent::setCreatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateAtValue', array());

        return parent::setUpdateAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropietario(\GestionBundle\Entity\Propietario $propietario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropietario', array($propietario));

        return parent::setPropietario($propietario);
    }

    /**
     * {@inheritDoc}
     */
    public function removePropietario(\GestionBundle\Entity\Propietario $propietario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePropietario', array($propietario));

        return parent::removePropietario($propietario);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropietario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropietario', array());

        return parent::getPropietario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUbicacion(\GestionBundle\Entity\Ubicacion $ubicaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUbicacion', array($ubicaciones));

        return parent::setUbicacion($ubicaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUbicacion(\GestionBundle\Entity\Ubicacion $ubicaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUbicacion', array($ubicaciones));

        return parent::removeUbicacion($ubicaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getUbicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUbicacion', array());

        return parent::getUbicacion();
    }

}
